### ISSUE TITLE
[PPC64LE] Fail to build cargo

### ISSUE THREAD

**Issue by runlevel5** [kornelski/mozjpeg-sys#18]
```
$ uname -a
Linux orion.dev 5.6.0-0.rc7.git1.2.local.fc33.ppc64le #1 SMP Sun Mar 29 10:28:55 AEDT 2020 ppc64le ppc64le ppc64le GNU/Linux

$ RUST_BACKTRACE=full cargo build 
   Compiling mozjpeg-sys v0.10.4 (/home/tle/src/mozjpeg-sys)
error: failed to run custom build command for `mozjpeg-sys v0.10.4 (/home/tle/src/mozjpeg-sys)`

Caused by:
  process didn't exit successfully: `/home/tle/src/mozjpeg-sys/target/debug/build/mozjpeg-sys-7b77e8c66fcb5bfb/build-script-build` (exit code: 101)
--- stdout
cargo:include=/home/tle/src/mozjpeg-sys/target/debug/build/mozjpeg-sys-be8744332012c634/out/include:/home/tle/src/mozjpeg-sys/vendor
cargo:lib_version=62

--- stderr
thread 'main' panicked at 'The mozjpeg-sys SIMD build script is incomplete for this platform', src/build.rs:210:15
stack backtrace:
   0:        0x1267560c4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdce29e1b8cbd58e8
   1:        0x126779094 - core::fmt::write::h78b16a428942fe61
   2:        0x126753db4 - std::io::Write::write_fmt::h9b102c09ee6e6c98
   3:        0x126740298 - std::panicking::default_hook::{{closure}}::h1e466679536499a6
   4:        0x12673ff1c - std::panicking::default_hook::hb14d0e2137b8efb2
   5:        0x126740b5c - std::panicking::rust_panic_with_hook::hb6f94587a2c85916
   6:        0x1266b5654 - std::panicking::begin_panic::hcabcef97dbc39bb9
                               at /builddir/build/BUILD/rustc-1.42.0-src/src/libstd/panicking.rs:399
   7:        0x12662dcf8 - build_script_build::build_gas::h72656cc4f42354ee
                               at src/build.rs:210
   8:        0x12662d418 - build_script_build::main::h0bd3c5cc4a8f6c94
                               at src/build.rs:169
   9:        0x126631974 - std::rt::lang_start::{{closure}}::h2d1578b8f062a088
                               at /builddir/build/BUILD/rustc-1.42.0-src/src/libstd/rt.rs:67
  10:        0x1267568e4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h11254ab1e48024cd
  11:        0x1267403bc - std::panicking::try::do_call::hd653e821b721f2a3
  12:        0x12675d920 - __rust_try
  13:        0x12675d78c - __rust_maybe_catch_panic
  14:        0x126746a78 - std::rt::lang_start_internal::h59c0cad074641a7a
  15:        0x12663190c - std::rt::lang_start::he9c8792b3960e5d7
                               at /builddir/build/BUILD/rustc-1.42.0-src/src/libstd/rt.rs:67
  16:        0x12662e9d0 - main
  17:     0x7fffbd2f80cc - generic_start_main
                               at ../csu/libc-start.c:308
  18:     0x7fffbd2f8290 - __libc_start_main
                               at ../sysdeps/unix/sysv/linux/powerpc/libc-start.c:98
  19:                0x0 - <unknown>
```

The error is at https://github.com/kornelski/mozjpeg-sys/blob/master/src/build.rs#L211

It's seems to me ppc64le is not supported with `with_simd` feature OR have I missed something?

**Comment by kornelski** [comment]
Like the message says, the build.rs script is incomplete. I don't have PPC to test on, so I didn't add it.

Please see what libjpeg-turbo does on PPC (whether it uses nasm or gas) and add the files that PPC needs.

**Comment by runlevel5** [comment]
@kornelski I'll see what I could do. Wondering if you would be able to work on ppc64le if you could have access to the platform? I am happy to grant you SSH access to my box. Please feel free to reply with your public SSH key.

**Comment by kornelski** [comment]
I'm happy to merge a pull request, but I don't have time to implement it.
